# 🔧 Your GitHub username and repo name
owner: XSephiie
repo: rbxplugin-status

sites:
  - name: RBX Plugin
    url: https://rbx-plugin.onrender.com
    method: GET
    expectedStatus: 200

status-website:
  # If you don't have a custom domain, use baseUrl instead of cname
  # Uncomment the next line and replace with your repo name
  baseUrl: /rbxplugin-status

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RBX Plugin Status
  introTitle: "RBX Plugin Status"
  introMessage: Monitoring uptime for [RBX Plugin](https://rbxpluginv1.onrender.com) every 5 minutes using GitHub Actions.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/your-github-username/rbxplugin-status
